[project]
name = "jet-docs"
version = "0.0.0"
description = "unofficial JET API docs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
mkdocs-gen-files = "^0.5.0"
mkdocs-literate-nav = "^0.6.1"
mkdocs-material = "^9.5.41"
mkdocs-minify-plugin = "^0.8.0"
mkdocs-redirects = "^1.2.1"
mkdocstrings = { version = "^0.26.2", extras = ["python"] }
mypy = "^1.12.0"
ruff = "^0.6.9"

vsaa = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-aa.git", rev = "a0e40a389ea0cb26f019483030918b13e07cf0fd" }
vsadjust = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-adjust.git", rev = "06a59af8f093d6fd67a5c8a876a20c507a26cf44" }
vsdeband = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-deband.git", rev = "38cff97eca8103980d3e70da1f4d496532c73dec" }
vsdehalo = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-dehalo.git", rev = "9cbfdf57809dca5cdd3c95f108ef96306758faa0" }
vsdeinterlace = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-deinterlace.git", rev = "961c7a1ae1afc7ac5caaa3c6fbd17477ee5d42ef" }
vsdenoise = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise.git", rev = "2a0e2ae4618cd0c56a6e46c63d32a0011475106b" }
vsexprtools = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-exprtools.git", rev = "96f745bdf3ba9c89860fa00c3ee4a027e8b50ec7" }
vskernels = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-kernels.git", rev = "1e551a3ee5e30be1e50d8e097e072e81591d1234" }
vsmasktools = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-masktools.git", rev = "a15da07a790aef6819ac720ba23dbd9dc52d6d18" }
vspreview = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview.git", rev = "e0fc35ecf187bb3594c7da802be271d13e019636" }
vspyplugin = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-pyplugin.git", rev = "9ec87e79ece0c830dd6a643f537f507211b4fc33" }
vsrgtools = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-rgtools.git", rev = "389d5d91f3453beaee6be8a7401c6771ee29f91c" }
vsscale = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-scale.git", rev = "4b317a3feab4be79c692946c266f6275d905dfb9" }
vssource = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-source.git", rev = "04b599c034cb336fba4b3ded0c7992006e5263fa" }
vstools = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git", rev = "ea70fce373b56f431cf1557d17c40c0ac7941440" }
vstransitions = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-transitions.git", rev = "5f4cfc3d67f69dc78a9026a366b1dd0316297ac6" }

[tool.mypy]
check_untyped_defs = true
color_output = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
error_summary = true
no_implicit_optional = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = false
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",       # pydocstyle
    "FIX002",  # Line contains TODO, consider resolving the issue.
    "INP001",
    "TD002",   # Missing author in TODO.
    "TD003",   # Missing issue link on the line following this TODO.
]
