[project]
name = "jet-docs"
version = "0.0.0"
description = "unofficial JET API docs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
mkdocs-gen-files = "^0.5.0"
mkdocs-literate-nav = "^0.6.1"
mkdocs-material = "^9.5.44"
mkdocs-minify-plugin = "^0.8.0"
mkdocs-redirects = "^1.2.2"
mkdocstrings = { version = "^0.27.0", extras = ["python"] }
mypy = "^1.13.0"
ruff = "^0.7.3"

vsaa = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-aa.git", rev = "a0e40a389ea0cb26f019483030918b13e07cf0fd" }
vsadjust = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-adjust.git", rev = "06a59af8f093d6fd67a5c8a876a20c507a26cf44" }
vsdeband = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-deband.git", rev = "3b60482187260988e680835e5c43dd30d13621da" }
vsdehalo = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-dehalo.git", rev = "9cbfdf57809dca5cdd3c95f108ef96306758faa0" }
vsdeinterlace = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-deinterlace.git", rev = "50931a2e81d2695c0c9e66b32044d6d850af79cf" }
vsdenoise = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise.git", rev = "704b361810e3c830cf90aac3537e07902066b815" }
vsexprtools = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-exprtools.git", rev = "889a7bb7f03207751b2c7f42b9200ce41d467f44" }
vskernels = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-kernels.git", rev = "b04b604e57bd8d6264dbae01edc630677ffd42e5" }
vsmasktools = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-masktools.git", rev = "cef169326ff00191a436babf0bb93a94c2671176" }
vspreview = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview.git", rev = "e0fc35ecf187bb3594c7da802be271d13e019636" }
vspyplugin = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-pyplugin.git", rev = "9ec87e79ece0c830dd6a643f537f507211b4fc33" }
vsrgtools = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-rgtools.git", rev = "848c8347f62798924bb4ae59856358eb9fc9eceb" }
vsscale = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-scale.git", rev = "cf0c91b1432155d03a44d942da55549bee2a42c3" }
vssource = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-source.git", rev = "0379acf20dad9134d4d8d1239936a3d218117192" }
vstools = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git", rev = "b1e7a73dce5eab518e388eb2d27eede8e6ddccc3" }
vstransitions = { git = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-transitions.git", rev = "5f4cfc3d67f69dc78a9026a366b1dd0316297ac6" }

[tool.mypy]
check_untyped_defs = true
color_output = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
error_summary = true
no_implicit_optional = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = false
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",       # pydocstyle
    "FIX002",  # Line contains TODO, consider resolving the issue.
    "INP001",
    "TD002",   # Missing author in TODO.
    "TD003",   # Missing issue link on the line following this TODO.
]
