name: Set up VapourSynth
description: Build and install VapourSynth
inputs:
  vapoursynth-version:
    description: VapourSynth version
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v16

    - name: Set up Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: Install VapourSynth
      shell: bash
      run: nix profile install nixpkgs#python312Packages.vapoursynth

    - shell: bash
      run: uv pip install --system -U vapoursynth

    - name: Verify VapourSynth install
      shell: python
      run: |
        import vapoursynth
        print(vapoursynth.core)
