name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      PROD: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version-file: .python-version
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Install VapourSynth
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: R70

      - name: Install dependencies
        run: poetry install

      - name: Restore build cache
        uses: actions/cache/restore@v4.1.0
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Build
        run: poetry run mkdocs build

      - name: Upload
        uses: actions/upload-artifact@v4.4.0
        with:
          name: site
          path: site

      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: site

      - name: Save build cache
        uses: actions/cache/save@v4.1.0
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache

  mypy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version-file: .python-version
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Install VapourSynth
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: R70

      - name: Install dependencies
        run: poetry install

      - name: mypy
        run: poetry run mypy .

  ruff:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version-file: .python-version
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Install VapourSynth
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: R70

      - name: Install dependencies
        run: poetry install

      - name: Ruff
        run: poetry run ruff check .

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build, mypy, ruff]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
