name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      PROD: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6.0.0
        with:
          enable-cache: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Set up Nix cache
        uses: cachix/cachix-action@v16
        with:
          name: sgt0
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Install dependencies
        run: nix develop --command uv sync --locked

      - name: Restore build cache
        uses: actions/cache/restore@v4.2.3
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Build
        run: nix develop --command uv run mkdocs build

      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: site
          path: site

      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: site

      - name: Save build cache
        uses: actions/cache/save@v4.2.3
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache

  mypy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6.0.0
        with:
          enable-cache: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Set up Nix cache
        uses: cachix/cachix-action@v16
        with:
          name: sgt0
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Install dependencies
        run: nix develop --command uv sync --locked

      - name: mypy
        run: nix develop --command uv run mypy .

  ruff:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6.0.0
        with:
          enable-cache: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Set up Nix cache
        uses: cachix/cachix-action@v16
        with:
          name: sgt0
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Install dependencies
        run: nix develop --command uv sync --locked

      - name: Ruff
        run: nix develop --command uv run ruff check .

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build, mypy, ruff]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
